package runner

import (
	"context"
	"strings"
	"testing"
	"time"

	embedded "bash-teacher/content"
	"bash-teacher/internal/content"
)

func testLibrary(t *testing.T) *content.Library {
	t.Helper()
	lib, err := content.Load(embedded.FS)
	if err != nil {
		t.Fatalf("load content: %v", err)
	}
	return lib
}

func testRunner(t *testing.T, opts ...Option) *Runner {
	t.Helper()
	return New(testLibrary(t), opts...)
}

// TestReferenceSolutionsPass is the content-drift guard SPEC §10 requires: it
// runs every exercise's reference solution in the sandbox and asserts it still
// produces the committed expected output. Expected files are generated by
// running the solution, so this test is what stops them from being edited by
// hand into something the solution no longer prints.
func TestReferenceSolutionsPass(t *testing.T) {
	r := testRunner(t)
	lib := r.lib
	if len(lib.Exercises) == 0 {
		t.Fatal("no exercises to check")
	}
	for _, ex := range lib.Exercises {
		t.Run(ex.ID, func(t *testing.T) {
			out, err := r.RunExercise(t.Context(), ex, ex.ReferenceSolution)
			if err != nil {
				t.Fatalf("run: %v", err)
			}
			if !out.Ran() {
				t.Fatalf("reference solution was refused before execution:\n%s", out.Refusal())
			}
			if !out.Passed {
				t.Errorf("reference solution %q did not produce the expected output\n%s\nstderr: %s",
					ex.ReferenceSolution, out.Diff, out.Stderr)
			}
		})
	}
}

func TestRunCapturesStdoutAndExitCode(t *testing.T) {
	r := testRunner(t)
	res, err := r.Run(t.Context(), Job{Input: "head -1 access.log", Fixture: "weblogs"})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !res.Ran() {
		t.Fatalf("refused: %s", res.Refusal())
	}
	if res.ExitCode != 0 {
		t.Errorf("exit code = %d, stderr = %q", res.ExitCode, res.Stderr)
	}
	if strings.Count(strings.TrimRight(res.Stdout, "\n"), "\n") != 0 || res.Stdout == "" {
		t.Errorf("stdout = %q, want exactly one line", res.Stdout)
	}
}

// TestFixtureIsAThrowawayCopy checks that mutating the fixture in one run
// cannot be observed by the next.
func TestFixtureIsAThrowawayCopy(t *testing.T) {
	r := testRunner(t)
	if _, err := r.Run(t.Context(), Job{Input: "rm access.log", Fixture: "weblogs"}); err != nil {
		t.Fatalf("first run: %v", err)
	}
	res, err := r.Run(t.Context(), Job{Input: "wc -l access.log", Fixture: "weblogs"})
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if res.ExitCode != 0 {
		t.Errorf("access.log did not come back after being deleted: exit %d, stderr %q",
			res.ExitCode, res.Stderr)
	}
}

func TestTimeoutKillsTheRun(t *testing.T) {
	r := testRunner(t, WithTimeout(500*time.Millisecond))
	start := time.Now()
	res, err := r.Run(t.Context(), Job{Input: "sleep 30", Fixture: "weblogs"})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !res.TimedOut {
		t.Errorf("run was not marked as timed out (exit %d)", res.ExitCode)
	}
	if elapsed := time.Since(start); elapsed > 5*time.Second {
		t.Errorf("timeout took %s to take effect", elapsed)
	}
}

func TestOutputIsTruncated(t *testing.T) {
	r := testRunner(t, WithTimeout(3*time.Second))
	res, err := r.Run(t.Context(), Job{Input: "yes bash-teacher", Fixture: "weblogs"})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !res.StdoutTruncated {
		t.Errorf("unbounded output was not truncated (%d bytes captured)", len(res.Stdout))
	}
	if len(res.Stdout) > outputLimit {
		t.Errorf("captured %d bytes, over the %d-byte limit", len(res.Stdout), outputLimit)
	}
}

func TestNoExecRefusesToRun(t *testing.T) {
	r := testRunner(t, WithNoExec(true))
	res, err := r.Run(t.Context(), Job{Input: "head -1 access.log", Fixture: "weblogs"})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if res.Ran() || !res.Skipped {
		t.Errorf("--no-exec still executed: %+v", res)
	}
}

func TestConstraintsAreEnforced(t *testing.T) {
	r := testRunner(t)
	res, err := r.Run(context.Background(), Job{
		Input: "grep -c ERROR app.log", Fixture: "weblogs",
		MustUse: []string{"awk"}, Forbid: []string{"grep"},
	})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if res.Ran() {
		t.Fatal("constraint violations did not stop execution")
	}
	if len(res.Violations) != 2 {
		t.Fatalf("got %d violations, want 2: %v", len(res.Violations), res.Violations)
	}
	for _, v := range res.Violations {
		if v.Kind != KindConstraint {
			t.Errorf("violation %q has kind %q, want %q", v.Message, v.Kind, KindConstraint)
		}
	}
}
